//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTable
    {
        public int GameId { get; set; }
        public Nullable<int> OneOfHearts { get; set; }
        public Nullable<int> TwoOfHearts { get; set; }
        public Nullable<int> ThreeOfHearts { get; set; }
        public Nullable<int> FourOfHearts { get; set; }
        public Nullable<int> FiveOfHearts { get; set; }
        public Nullable<int> SixOfHearts { get; set; }
        public Nullable<int> SevenOfHearts { get; set; }
        public Nullable<int> EightOfHearts { get; set; }
        public Nullable<int> NineOfHearts { get; set; }
        public Nullable<int> TenOfHearts { get; set; }
        public Nullable<int> JackOfHearts { get; set; }
        public Nullable<int> QueenOfHearts { get; set; }
        public Nullable<int> KingOfHearts { get; set; }
        public Nullable<int> OneOfSpades { get; set; }
        public Nullable<int> TwoOfSpades { get; set; }
        public Nullable<int> ThreeOfSpades { get; set; }
        public Nullable<int> FourOfSpades { get; set; }
        public Nullable<int> FiveOfSpades { get; set; }
        public Nullable<int> SixOfSpades { get; set; }
        public Nullable<int> SevenOfSpades { get; set; }
        public Nullable<int> EightOfSpades { get; set; }
        public Nullable<int> NineOfSpades { get; set; }
        public Nullable<int> TenOfSpades { get; set; }
        public Nullable<int> JackOfSpades { get; set; }
        public Nullable<int> QueenOfSpades { get; set; }
        public Nullable<int> KingOfSpades { get; set; }
        public Nullable<int> OneOfClover { get; set; }
        public Nullable<int> TwoOfClover { get; set; }
        public Nullable<int> ThreeOfClover { get; set; }
        public Nullable<int> FourOfClover { get; set; }
        public Nullable<int> FiveOfClover { get; set; }
        public Nullable<int> SixOfClover { get; set; }
        public Nullable<int> SevenOfClover { get; set; }
        public Nullable<int> EightOfClover { get; set; }
        public Nullable<int> NineOfClover { get; set; }
        public Nullable<int> TenOfClover { get; set; }
        public Nullable<int> JackOfClover { get; set; }
        public Nullable<int> QueenOfClover { get; set; }
        public Nullable<int> KingOfClover { get; set; }
        public Nullable<int> OneOfDiamond { get; set; }
        public Nullable<int> TwoOfDiamond { get; set; }
        public Nullable<int> ThreeOfDiamond { get; set; }
        public Nullable<int> FourOfDiamond { get; set; }
        public Nullable<int> FiveOfDiamond { get; set; }
        public Nullable<int> SixOfDiamond { get; set; }
        public Nullable<int> SevenOfDiamond { get; set; }
        public Nullable<int> EightOfDiamond { get; set; }
        public Nullable<int> NineOfDiamond { get; set; }
        public Nullable<int> TenOfDiamond { get; set; }
        public Nullable<int> JackOfDiamond { get; set; }
        public Nullable<int> QueenOfDiamond { get; set; }
        public Nullable<int> KingOfDiamond { get; set; }
        public Nullable<int> FirstJoker { get; set; }
        public Nullable<int> SecondJoker { get; set; }
        public Nullable<int> ThirdJoker { get; set; }
    
        public virtual GameInfo GameInfo { get; set; }
    }
}
