//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_DAL
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class CardTable
    {
		public int GameId { get; set; }
		
		public int OneOfHearts { get; set; } = 1;
		
		public int TwoOfHearts { get; set; } = 1;
		
		public int ThreeOfHearts { get; set; } = 1;
		
		public int FourOfHearts { get; set; } = 1;
		
		public int FiveOfHearts { get; set; } = 1;
		
		public int SixOfHearts { get; set; } = 1;
		
		public int SevenOfHearts { get; set; } = 1;
		
		public int EightOfHearts { get; set; } = 1;
		
		public int NineOfHearts { get; set; } = 1;
		
		public int TenOfHearts { get; set; } = 1;
		
		public int JackOfHearts { get; set; } = 1;
		
		public int QueenOfHearts { get; set; } = 1;
		
		public int KingOfHearts { get; set; } = 1;
		
		public int OneOfSpades { get; set; } = 1;
		
		public int TwoOfSpades { get; set; } = 1;
		
		public int ThreeOfSpades { get; set; } = 1;
		
		public int FourOfSpades { get; set; } = 1;
		
		public int FiveOfSpades { get; set; } = 1;
		
		public int SixOfSpades { get; set; } = 1;
		
		public int SevenOfSpades { get; set; } = 1;
		
		public int EightOfSpades { get; set; } = 1;
		
		public int NineOfSpades { get; set; } = 1;
		
		public int TenOfSpades { get; set; } = 1;
		
		public int JackOfSpades { get; set; } = 1;
		
		public int QueenOfSpades { get; set; } = 1;
		
		public int KingOfSpades { get; set; } = 1;
		
		public int OneOfClover { get; set; } = 1;
		
		public int TwoOfClover { get; set; } = 1;
		
		public int ThreeOfClover { get; set; } = 1;
		
		public int FourOfClover { get; set; } = 1;
		
		public int FiveOfClover { get; set; } = 1;
		
		public int SixOfClover { get; set; } = 1;
		
		public int SevenOfClover { get; set; } = 1;
		
		public int EightOfClover { get; set; } = 1;
		
		public int NineOfClover { get; set; } = 1;
		
		public int TenOfClover { get; set; } = 1;
		
		public int JackOfClover { get; set; } = 1;
		
		public int QueenOfClover { get; set; } = 1;
		
		public int KingOfClover { get; set; } = 1;
		
		public int OneOfDiamond { get; set; } = 1;
		
		public int TwoOfDiamond { get; set; } = 1;
		
		public int ThreeOfDiamond { get; set; } = 1;

        public int FourOfDiamond { get; set; } = 1;

        public int FiveOfDiamond { get; set; } = 1;

        public int SixOfDiamond { get; set; } = 1;

        public int SevenOfDiamond { get; set; } = 1;

        public int EightOfDiamond { get; set; } = 1;

        public int NineOfDiamond { get; set; } = 1;

        public int TenOfDiamond { get; set; } = 1;

        public int JackOfDiamond { get; set; } = 1;

        public int QueenOfDiamond { get; set; } = 1;

        public int KingOfDiamond { get; set; } = 1;

        public int FirstJoker { get; set; } = 1;

        public int SecondJoker { get; set; } = 1;

        public int ThirdJoker { get; set; } = 1;
    
        public virtual GameInfo GameInfo { get; set; }
    }
}
